version: '3.9'
services:
  qrlink-db:
    container_name: qrlink-db
    image: ubuntu/mysql:8.0-20.04_beta
    restart: always
    ports:
      - "33306:3306"
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: "l=,m%hL*YUStEP+,0uVR"
      MYSQL_DATABASE: qrlink
    networks:
      - qrlink
    volumes:
      - ./mysql_data:/var/lib/mysql
  
  qrlink:
    container_name: qrlink
    restart: always
    depends_on:
      - qrlink-db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8102:443"
    networks:
      - qrlink
    volumes:
      - /var/www/websites/qrlink.net.br:/var/www/html
      - ./apache_logs:/var/log/apache2

networks:
  qrlink:
